apiVersion: v1
kind: Pod
metadata:
  name: glcs-server
spec:
  volumes:
    - name: shared-workspace
      emptyDir: {}
  containers:
  - name: glcs
    image: glcs:latest 
    imagePullPolicy: Never
    volumeMounts:
      - name: shared-workspace
        mountPath: /shared-workspace
    ports:
      - containerPort: 8090
  - name: pgasgraph 
    image: pgasgraph:latest 
    imagePullPolicy: Never
    volumeMounts:
      - name: shared-workspace
        mountPath: /shared-workspace
